FROM openknowledge/ckan-dev:2.9

MAINTAINER Your Name Here <you@example.com>

# Set timezone
ARG TZ
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime
RUN echo $TZ > /etc/timezone



# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)
# For instance:
#RUN pip install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages && \
#    pip install -e git+https://github.com/ckan/ckanext-dcat.git@v0.0.6#egg=ckanext-dcat && \
#    pip install -r https://raw.githubusercontent.com/ckan/ckanext-dcat/v0.0.6/requirements.txt


# Set src dirs
ENV SRC_DIR=/srv/app/src
ENV PIP_SRC=${SRC_DIR}
ENV APP_DIR=/srv/app
ENV SRC_EXTENSIONS_DIR=/srv/app/src_extensions


RUN mkdir -p $SRC_EXTENSIONS_DIR
RUN chown -R ckan:ckan ${SRC_EXTENSIONS_DIR}
RUN ls -lah ${SRC_EXTENSIONS_DIR}
COPY src/src_extensions/ ${SRC_EXTENSIONS_DIR}
RUN ls -lah ${SRC_EXTENSIONS_DIR}

# RUN curl -o ${SRC_DIR}/get-pip.py https://bootstrap.pypa.io/get-pip.py && \   
#     python ${SRC_DIR}/get-pip.py &&  \  
#     pip install supervisor

# RUN rm -rf ${SRC_DIR}/get-pip.py

# RUN pip install -e git+${GIT_URL}@${GIT_BRANCH}#egg=ckan
RUN pip install -r ${SRC_EXTENSIONS_DIR}/ckanext-aircan/requirements.txt
RUN pip install -r ${SRC_EXTENSIONS_DIR}/ckanext-aircan/dev-requirements.txt
RUN pip install -e ${SRC_EXTENSIONS_DIR}/ckanext-aircan

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
# See https://github.com/okfn/docker-ckan#applying-patches
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
